name: validate-SVG
on: push

permissions:
  checks: write
  pull-requests: write

jobs:
  validate-linter:
    name: Run SVG Linter
    runs-on: ubuntu-latest
    steps:
    
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Run SVG Linter
      uses: "szepeviktor/svg-validator@v1.0.0"
      with:
        svg_path: "/**/*.svg"